### PR TITLE
adding df utils and flake8 conf, pyproject.toml, and requirements.txt

### PR DESCRIPTION
**Pull request by matthewmturner**
This is my baseline utils code i had been working on.  I also add .flake8 file.

### CODE REVIEW

**Comment by matthewmturner** [comment]
@jordan-carson Dont approve this yet until i resolve the issues.

**Comment by matthewmturner** [comment]
also added conda environment.yml file

**Comment by jordan-carson** [comment]
The last function `describe_stats` will only work if the dataframe has been transformed to a described dataframe, i.e. df.describe(), on a data frame that has been described. Could you modify the function to ensure that these columns exist in the passed data frame, or ensure that the dataframe is a described dataframe, otherwise this function will fail. 

You can even force the dataframe to df = df.describe(), within the function call.

**Comment by jordan-carson** [comment]
This is good to go but be sure to revisit your function

**Pull request merged**
