### PR TITLE
Add baseline testing

### PR DESCRIPTION
**Pull request by matthewmturner**
added a couple tests for df_utils and fixed file structure for rice.

### CODE REVIEW

**Comment by matthewmturner** [comment]
i got the baseline setup in place. plz review and merge when you get the chance.  will create separate issues to create tests for the other files and we'll do it incrementally.

**Comment by jordan-carson** [comment]
shouldn't we import the function instead of redeclaring it in the tests folder?

**Comment by jordan-carson** [comment]
then run your tests so were always tests the most up-to-date func

**Comment by matthewmturner** [comment]
thats what its doing. the function in the test py file is the test.

**Pull request merged**
